from yacs.config import CfgNode as CN

_C = CN()

_C.TRAIN = CN()
_C.TRAIN.EPOCHS = 10
_C.TRAIN.LABEL_SMOOTHING = 0.00
_C.TRAIN.USE_SCALER = True
_C.TRAIN.MAX_NORM = 100
_C.TRAIN.ACCUM_ITER = 1

_C.DATA = CN()
_C.DATA.BATCH_SIZE = 16
_C.DATA.DATASET = "harup"
_C.DATA.SUBSET = ""
_C.DATA.IN_CHANNELS = 3
_C.DATA.NUM_CLASSES = 11
_C.DATA.SENSOR_DIM=15
# _C.DATA.IMG_SIZE = 224
# _C.DATA.NUM_NODE = 55
# _C.DATA.SEQ_LEN = 50

_C.MODEL = CN()
_C.MODEL.NAME = "stgcn"

_C.GRAPH = CN()
_C.GRAPH.LAYOUT = "coco_cut"
_C.GRAPH.STRATEGY = "spatial"

# _C.MODEL.TRANSFORMER = CN()
# _C.MODEL.TRANSFORMER.EMBEDDING_DIM = 128
# _C.MODEL.TRANSFORMER.NUM_BLOCKS = 10
# _C.MODEL.TRANSFORMER.HEAD_DIM = 64
# _C.MODEL.TRANSFORMER.NUM_HEADS = 8
# _C.MODEL.TRANSFORMER.FFN_EXPAND_RATIO = 4.0
# _C.MODEL.TRANSFORMER.FFN_DROPOUT_RATIO = 0.25
# _C.MODEL.TRANSFORMER.MAX_STOCHASTIC_DEPTH_RATIO = 0.25

# _C.MODEL.GRAPH = "models.graph.Graph"
# _C.MODEL.LAYOUT = "openpose"
# _C.MODEL.STRATEGY = "uniform"
# _C.MODEL.MAX_HOP = 1
# _C.MODEL.DILATION = 1

_C.OPTIM = CN()
_C.OPTIM.TYPE = "rmsprop"
_C.OPTIM.LR = 0.001
_C.OPTIM.MOMENTUM = 0.99
_C.OPTIM.WEIGHT_DECAY = 0.01
_C.OPTIM.BETAS = [0.9, 0.999]
_C.OPTIM.EPS = 1.0e-8

_C.LR_SCHEDULER = CN()
_C.LR_SCHEDULER.TYPE = None
_C.LR_SCHEDULER.T_INITIAL = 500
_C.LR_SCHEDULER.LR_MIN = 1.0e-5
_C.LR_SCHEDULER.T_IN_EPOCHS = True
_C.LR_SCHEDULER.WARMUP_T = 5
_C.LR_SCHEDULER.WARMUP_LR_INIT = 1.0e-4

_C.SEED = 42
_C.DEVICE = "cuda"
_C.SAVE_CHECKPOINT = True
_C.RESUME_FROM = None
_C.PRETRAINED_WEIGHT_PATH = None
_C.TEST_ONLY = False

_C.NUM_WORKERS = 8
_C.PIN_MEMORY = True

_C.LOG_DIR = None
_C.LOGGING_TIMING = 10
_C.TENSORBOARD_LOG = False
_C.TOP_K = [1]

def get_cfg_defaults():
  return _C.clone()
