TRAIN:
    EPOCHS: 100
    LABEL_SMOOTHING: 0.0
    USE_SCALER: True
    MAX_NORM: 100
    ACCUM_ITER: 1

DATA:
    BATCH_SIZE: 32
    DATASET: "harup_egawa"
    IN_CHANNELS: 3
    NUM_CLASSES: 11

MODEL:
    NAME: "stgcn"

OPTIM:
    TYPE: "rmsprop"
    LR: 0.001

LR_SCHEDULER:
    TYPE: None

SEED: 42
DEVICE: "cuda"
SAVE_CHECKPOINT: True
RESUME_FROM: None
PRETRAINED_WEIGHT_PATH: None
TEST_ONLY: False

NUM_WORKERS: 8
PIN_MEMORY: True

LOG_DIR: None
LOGGING_TIMING: 10
TENSORBOARD_LOG: False
TOP_K: [1]